"use client"
import React, { createContext, useContext, useState, useEffect } from 'react'
import { usePathname } from 'next/navigation'

type Language = 'es' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  es: {
    // Navbar
    'nav.services': 'Servicios',
    'nav.about': 'Sobre nosotros',
    'nav.blog': 'Blog',
    'nav.contact': 'Contacto',

    // Hero
    'hero.eyebrow': 'Agencia Shopify · España',
    'hero.title.line1': 'Shopify de nivel enterprise.',
    'hero.title.line2': 'Por fin accesible.',
    'hero.sub': 'Tienes tráfico, pero no convierte. Te ayudamos a arreglarlo con los mismos procesos que usan las grandes — al precio de tu etapa.',
    'hero.cta1': 'Habla con un experto',
    'hero.cta2': 'Ver servicios y precios',
    'hero.stat1.label': 'conversiones/mes — nuestro punto dulce',
    'hero.stat2.label': 'migración completa a Shopify, llave en mano',
    'hero.stat3.num': 'IA',
    'hero.stat3.label': 'procesos enterprise, costes de marca pequeña',

    // Problem + For whom (sección fusionada: afirmación corta + checklist)
    'problem.eyebrow': 'El problema',
    'problem.title': 'Las agencias persiguen a los grandes.',
    'problem.lede': 'Tu tienda no tiene un problema de producto. Tiene un problema de conversión — y lo sabes si esto te suena:',
    'whom.item1': 'Vendes en Shopify — o quieres migrar a Shopify.',
    'whom.item2': 'Entra tráfico, pero las conversiones no acompañan.',
    'whom.item3': 'Quieres crecer y no sabes por dónde empezar.',
    'whom.item4': 'No tienes presupuesto enterprise — y no deberías necesitarlo.',
    'whom.item5': 'Tu agencia, si la tienes, no está mirando por ti.',
    'whom.foot': 'Justo para quien estamos aquí.',

    // Close / CTA
    'close.eyebrow': 'Empecemos',
    'close.title': 'Tu tienda se merece algo mejor.',
    'close.cta': 'Empieza con una auditoría',

    // Contact Section
    'contact.title': 'Hablemos.',
    'contact.description': 'Cuéntanos qué está pasando con tu tienda. Te respondemos para coordinar una llamada, sin compromiso.',
    'contact.form.title': 'CUÉNTANOS TU PROYECTO',
    'contact.form.name': 'Tu nombre',
    'contact.form.name.label': 'Nombre *',
    'contact.form.email': 'tu@email.com',
    'contact.form.email.label': 'Email *',
    'contact.form.phone': 'Teléfono',
    'contact.form.company': 'Tu tienda / marca',
    'contact.form.company.label': 'Empresa',
    'contact.form.message': 'Cuéntanos sobre tu proyecto...',
    'contact.form.message.label': 'Mensaje *',
    'contact.form.submit': 'Enviar mensaje',
    'contact.form.sending': 'Enviando...',
    'contact.form.success': '¡Mensaje enviado correctamente! Te contactaremos pronto.',
    'contact.form.name.req': 'Dinos cómo te llamas',
    'contact.form.name.ok': 'Perfecto',
    'contact.form.email.req': 'Necesitamos tu email',
    'contact.form.email.bad': 'Ese email no parece válido',
    'contact.form.email.ok': 'Email válido',
    'contact.form.company.ok': 'Anotado',
    'contact.form.message.req': 'Cuéntanos algo sobre tu tienda',
    'contact.form.message.short': 'Un poco más de contexto, por favor',
    'contact.form.message.ok': 'Listo',
    'contact.form.err': 'Revisa los campos marcados.',
    'contact.info.phone': 'Teléfono',
    'contact.info.email': 'Email',
    'contact.info.location': 'Ubicación',

    // Footer
    'footer.newsletter.title': 'MANTENTE AL DÍA',
    'footer.newsletter.description': 'Recibe las últimas tendencias de e-commerce, tips de Shopify y noticias de nuestra agencia directamente en tu inbox.',
    'footer.newsletter.placeholder': 'tu@email.com',
    'footer.newsletter.button': 'Suscribirme',
    'footer.newsletter.sending': 'Enviando...',
    'footer.newsletter.success': '¡Revisa tu email para confirmar!',
    'footer.newsletter.already': '¡Ya estás suscrito!',
    'footer.newsletter.subscribed': '¡Suscrito!',
    'footer.newsletter.error': 'Error al suscribirse',
    'footer.newsletter.connection_error': 'Error de conexión. Inténtalo de nuevo.',
    'footer.company': 'SELLIFYWORKS',
    'footer.description': 'Agencia ecommerce especializada en Shopify. Creamos, optimizamos y hacemos crecer tiendas online que convierten.',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.privacy': 'Política de Privacidad',
    'footer.cookies': 'Política de Cookies',
    
    // Footer Services
    'footer.services.title': 'SERVICIOS',
    'footer.services.migration': 'Migración a Shopify',
    'footer.services.migrationPlus': 'Migración Plus',
    'footer.services.customDev': 'Desarrollos a medida',
    'footer.services.conversionResearch': 'Conversion research',
    'footer.services.conversionAudit': 'Auditoría de conversión',
    'footer.services.landingPages': 'Optimización de landing pages',
    'footer.services.emailAutomation': 'Email marketing automation',
    'footer.services.emailCampaigns': 'Campañas de email',
    'footer.services.maintenance': 'Mantenimiento',

    // Services Section (pricing)
    'services.eyebrow': 'Servicios y precios',
    'services.title': 'Precios claros.',
    'services.sub': 'Sin paquetes inflados ni letra pequeña. Eliges lo que tu tienda necesita ahora y escalas cuando tenga sentido.',
    'services.group.foundation.name': 'Fundación',
    'services.group.foundation.desc': 'Una tienda construida para vender, no solo para existir.',
    'services.group.conversion.name': 'Conversión',
    'services.group.conversion.desc': 'No necesitas más visitas, necesitas vender más a las que ya tienes.',
    'services.group.recurring.name': 'Recurrencia',
    'services.group.recurring.desc': 'Convierte una compra en un cliente que vuelve.',
    'services.migration.name': 'Migración a Shopify',
    'services.migration.tagline': 'Para migrar sin perder ventas',
    'services.migration.bullet1': 'Auditoría completa antes de mover nada',
    'services.migration.bullet2': 'Carga y copy de todo tu catálogo',
    'services.migration.bullet3': 'Cero tiempo de inactividad',
    'services.migrationPlus.name': 'Migración Plus',
    'services.migrationPlus.tag': 'Recomendado',
    'services.migrationPlus.tagline': 'Para tiendas que ya facturan +4.000€/mes',
    'services.migrationPlus.bullet1': 'Todo lo de Migración',
    'services.migrationPlus.bullet2': 'Conversion research incluido',
    'services.migrationPlus.bullet3': 'Lanzas optimizando desde el día uno',
    'services.customDev.name': 'Desarrollos a medida',
    'services.customDev.tagline': 'Para lo que no encaja en ningún plan',
    'services.customDev.bullet1': 'Integraciones con tus herramientas',
    'services.customDev.bullet2': 'Automatizaciones a medida',
    'services.customDev.bullet3': 'Presupuesto cerrado antes de empezar',
    'services.customDev.price': 'A medida',
    'services.conversionResearch.name': 'Conversion research',
    'services.conversionResearch.tagline': 'Para entender por qué no compran',
    'services.conversionResearch.bullet1': 'Análisis de Google Analytics',
    'services.conversionResearch.bullet2': 'Investigación cualitativa real',
    'services.conversionResearch.bullet3': 'Informe accionable, sin jerga',
    'services.conversionAudit.name': 'Auditoría de conversión',
    'services.conversionAudit.tagline': 'Para saber qué arreglar primero',
    'services.conversionAudit.bullet1': 'Revisión completa del funnel',
    'services.conversionAudit.bullet2': 'Priorizado por impacto en ventas',
    'services.conversionAudit.bullet3': 'Próximos pasos concretos',
    'services.landingPages.name': 'Optimización de landing pages',
    'services.landingPages.tagline': 'Para tu página con más tráfico',
    'services.landingPages.bullet1': 'Heurísticas de CRO probadas',
    'services.landingPages.bullet2': 'CTAs y trust signals optimizados',
    'services.landingPages.bullet3': 'Precio por página, sin paquetes',
    'services.emailAutomation.name': 'Email marketing automation',
    'services.emailAutomation.tagline': 'Para vender mientras duermes',
    'services.emailAutomation.bullet1': 'Welcome flow y carrito abandonado',
    'services.emailAutomation.bullet2': 'Post-compra y solicitud de reseña',
    'services.emailAutomation.bullet3': 'Configurado y probado, listo para usar',
    'services.emailCampaigns.name': 'Campañas mensuales de email',
    'services.emailCampaigns.tagline': 'Para no dejar enfriar tu lista',
    'services.emailCampaigns.bullet1': 'Estrategia mensual de contenidos',
    'services.emailCampaigns.bullet2': 'Diseño e implementación incluidos',
    'services.emailCampaigns.bullet3': '8 envíos al mes',
    'services.maintenance.name': 'Mantenimiento',
    'services.maintenance.tagline': 'Para no quedar abandonada entre proyectos',
    'services.maintenance.bullet1': '10 tareas pequeñas al mes',
    'services.maintenance.bullet2': 'Sin contratar a nadie',
    'services.maintenance.bullet3': 'Tareas grandes, cotizadas aparte',
    'services.unit.iva': '+ IVA',
    'services.cta': 'Hablemos de tu tienda',
    'services.viewDetail': 'Ver detalle',
    'services.note': 'Los ejemplos de tareas de mantenimiento son orientativos. SellifyWorks decide, según el tiempo y la complejidad de cada tarea, si forma parte del mantenimiento o requiere un desarrollo aparte. Precios sin IVA.',

    // Case Study Section
    'casestudy.badge': 'Caso real',
    'casestudy.title': 'Can Ramos: de Wix estancado a Shopify que vende solo',
    'casestudy.subtitle': 'Tenían tráfico. La plataforma no los dejaba convertirlo.',
    'casestudy.challenge.title': 'El problema',
    'casestudy.challenge.description': 'Carga lenta, checkout confuso y cero email marketing. Can Ramos ya tenía clientes — cada visita que no convertía era venta perdida.',
    'casestudy.solution.title': 'Lo que hicimos',
    'casestudy.solution.description': 'Migración a Shopify sin perder un dato ni una venta. Tienda con su identidad real, upsells en el checkout y un welcome flow que vende solo.',
    'casestudy.results.title': 'El resultado',
    'casestudy.result1': 'Diseño con identidad propia: más confianza, más conversión',
    'casestudy.result2': 'Welcome flow vendiendo en automático, 24/7',
    'casestudy.result3': 'Ticket promedio más alto con upsells en checkout',
    'casestudy.result4': 'Carga más rápida, menos abandono en checkout',
    'casestudy.result5': 'Cero pérdidas: productos, clientes y SEO intactos',
    'casestudy.expertise.title': 'Por qué funcionó',
    'casestudy.expertise.description': 'Auditamos qué frenaba las ventas, rediseñamos con foco en conversión y automatizamos lo que antes era manual.',
    'casestudy.expertise.tag1': 'Diseño con identidad',
    'casestudy.expertise.tag2': 'Email automatizado',
    'casestudy.expertise.tag3': 'Más ticket promedio',
    'casestudy.cta.title': '¿Tu tienda te está limitando?',
    'casestudy.cta.description': 'Si tienes tráfico pero sientes que deberías vender más, hablemos. Te mostramos qué está frenando tus conversiones.',
    'casestudy.cta.button': 'Quiero una llamada gratuita',
    'casestudy.cta.viewcase': 'Ver la tienda real',
    
    // About Page
    'about.hero.title': 'SOBRE NOSOTROS',
    'about.hero.subtitle': 'Creamos experiencias de comercio electrónico excepcionales en Shopify.',
    'about.history.title': 'NUESTRA HISTORIA',
    'about.history.content': 'Este proyecto comenzó con una visión clara: mejorar la experiencia de compra en ecommerce mediante soluciones técnicas de alta calidad, enfocadas en Shopify. A partir de esa idea, SellifyWorks fue creciendo como una consultora técnica orientada a resultados reales, con un modelo de trabajo ágil, escalable y centrado en el cliente.',
    'about.mission.title': 'NUESTRA MISIÓN',
    'about.mission.content': 'Impulsamos negocios en ecommerce a través de soluciones técnicas personalizadas en Shopify. Nos enfocamos en automatizar procesos, optimizar el rendimiento de las tiendas y aplicar metodologías ágiles que aseguren entregas rápidas y de alta calidad.\n\nNuestro objetivo es que cada cliente pueda escalar sin preocuparse por la complejidad técnica, confiando en una consultora que pone la experiencia de usuario y la eficiencia operativa en el centro de cada decisión.',
    'about.values.title': 'NUESTROS VALORES',
    'about.values.subtitle': 'Los principios que guían nuestro trabajo y definen quiénes somos.',
    'about.values.quality.title': 'CALIDAD',
    'about.values.quality.content': 'Aplicamos prácticas de desarrollo como Extreme Programming porque creemos que una buena solución no solo debe funcionar, sino hacerlo bien, rápido y de forma sostenible.',
    'about.values.validation.title': 'VALIDACIÓN',
    'about.values.validation.content': 'Creemos en la importancia de validar ideas y soluciones a través de pruebas constantes y feedback real. Esto nos permite ajustar y mejorar nuestros enfoques, asegurando que siempre estamos en el camino correcto.',
    'about.values.transparency.title': 'TRANSPARENCIA',
    'about.values.transparency.content': 'Creemos en relaciones honestas, en procesos iterativos que permitan evolucionar constantemente, y en el compromiso innegociable de entregar valor en cada entrega.',
    'about.team.title': 'NUESTRO EQUIPO',
    'about.team.subtitle': 'Conoce a las personas que hacen posible el éxito de tu proyecto.',
    'about.team.mathias.role': 'FOUNDER',
    'about.team.mathias.description': 'Ingeniero en informática con mas de 10 años de experiencia en desarrollo de software.',
    'about.cta.title': '¿LISTO PARA TRABAJAR JUNTOS?',
    'about.cta.subtitle': 'Descubre cómo podemos ayudarte a llevar tu negocio al siguiente nivel.',
    'about.cta.button': 'Contactar con nosotros',
    
    // Newsletter Confirmed Page
    'newsletter.confirmed.success.title': '¡Suscripción Confirmada!',
    'newsletter.confirmed.success.message': 'Gracias por confirmar tu suscripción a nuestra newsletter. Ahora recibirás nuestros tips exclusivos sobre Shopify y comercio electrónico.',
    'newsletter.confirmed.already.title': '¡Ya estás suscrito!',
    'newsletter.confirmed.already.message': 'Tu email ya está suscrito a nuestra newsletter. No es necesario confirmar nuevamente.',
    'newsletter.confirmed.error.title': 'Error de Confirmación',
    'newsletter.confirmed.error.message': 'Hubo un problema al confirmar tu suscripción. El enlace puede haber expirado o ser inválido.',
    'newsletter.confirmed.back': 'Volver al Inicio',
    'newsletter.confirmed.loading': 'Cargando...',
    
    // 404 Page
    '404.title': 'PÁGINA NO ENCONTRADA',
    '404.description': 'Parece que la página que buscas se fue de vacaciones a una playa remota. Mientras tanto, ¿qué tal si exploramos juntos lo que sí tenemos?',
    '404.suggestion': 'O tal vez nuestro desarrollador se tomó demasiados cafés y movió algo por error... 🤔',
    '404.buttons.home': 'Volver al Inicio',
    '404.buttons.back': 'Página Anterior',
    '404.buttons.contact': 'Contáctanos',
    
    // Privacy Policy Page
    'privacy.title': 'POLÍTICA DE PRIVACIDAD',
    'privacy.subtitle': 'Última actualización: Agosto 2025',
    'privacy.section1.title': 'Información que Recopilamos',
    'privacy.section1.content': 'En SellifyWorks, recopilamos información personal que nos proporcionas voluntariamente cuando te comunicas con nosotros, te suscribes a nuestro newsletter, o utilizas nuestros servicios.',
    'privacy.section2.title': 'Tipos de Datos',
    'privacy.section2.content': 'Los tipos de información personal que podemos recopilar incluyen:',
    'privacy.section2.item1': 'Nombre y apellidos',
    'privacy.section2.item2': 'Dirección de correo electrónico',
    'privacy.section2.item3': 'Número de teléfono',
    'privacy.section2.item4': 'Información sobre tu empresa o proyecto',
    'privacy.section3.title': 'Cómo Utilizamos tu Información',
    'privacy.section3.content': 'Utilizamos la información personal que recopilamos para proporcionarte nuestros servicios, responder a tus consultas, enviarte nuestro newsletter (si te has suscrito), y mejorar nuestros servicios.',
    'privacy.section4.title': 'Protección de Datos',
    'privacy.section4.content': 'Implementamos medidas de seguridad técnicas y organizativas apropiadas para proteger tu información personal contra el acceso no autorizado, alteración, divulgación o destrucción.',
    'privacy.section5.title': 'Tus Derechos',
    'privacy.section5.content': 'Tienes derecho a acceder, rectificar, eliminar y portar tus datos personales. También puedes oponerte al tratamiento y solicitar la limitación del mismo.',
    'privacy.contact.title': 'Contacto',
    'privacy.contact.content': 'Si tienes preguntas sobre esta política de privacidad, puedes contactarnos en:',
    'privacy.back': 'Volver al Inicio',
    
    // Cookie Policy Page
    'cookies.title': 'POLÍTICA DE COOKIES',
    'cookies.subtitle': 'Última actualización: Agosto 2025',
    'cookies.section1.title': '¿Qué son las Cookies?',
    'cookies.section1.content': 'Las cookies son pequeños archivos de texto que se almacenan en tu dispositivo cuando visitas nuestro sitio web. Nos ayudan a mejorar tu experiencia de navegación y a entender cómo utilizas nuestro sitio.',
    'cookies.section2.title': 'Tipos de Cookies que Utilizamos',
    'cookies.section2.essential.title': 'Cookies Esenciales',
    'cookies.section2.essential.content': 'Estas cookies son necesarias para el funcionamiento básico del sitio web y no se pueden desactivar.',
    'cookies.section2.analytics.title': 'Cookies de Análisis',
    'cookies.section2.analytics.content': 'Nos ayudan a entender cómo los visitantes interactúan con nuestro sitio web recopilando información de forma anónima.',
    'cookies.section2.preferences.title': 'Cookies de Preferencias',
    'cookies.section2.preferences.content': 'Recordamos tus preferencias, como el idioma seleccionado, para mejorar tu experiencia.',
    'cookies.section3.title': 'Control de Cookies',
    'cookies.section3.content': 'Puedes controlar y/o eliminar las cookies como desees. Puedes eliminar todas las cookies que ya están en tu dispositivo y configurar la mayoría de navegadores para evitar que se instalen.',
    'cookies.section4.title': 'Más Información',
    'cookies.section4.content': 'Si desactivas las cookies, es posible que algunas funciones del sitio web no funcionen correctamente.',
    'cookies.contact.title': 'Contacto',
    'cookies.contact.content': 'Si tienes preguntas sobre nuestra política de cookies, puedes contactarnos en:',
    'cookies.back': 'Volver al Inicio',
    
    // Related Services
    'relatedServices.title': 'SERVICIOS RELACIONADOS',
    'relatedServices.subtitle': 'Descubre otros servicios que pueden impulsar tu tienda Shopify',
    'relatedServices.learnMore': 'Más información',
    'relatedServices.services.migration.title': 'Migración a Shopify',
    'relatedServices.services.migration.description': 'Migra tu tienda a Shopify sin perder datos ni interrumpir las ventas.',
    'relatedServices.services.migrationPlus.title': 'Migración Plus',
    'relatedServices.services.migrationPlus.description': 'Migración + conversion research para lanzar optimizando desde el día uno.',
    'relatedServices.services.customDev.title': 'Desarrollos a medida',
    'relatedServices.services.customDev.description': 'Funcionalidad personalizada, integraciones y automatizaciones.',
    'relatedServices.services.conversionResearch.title': 'Conversion research',
    'relatedServices.services.conversionResearch.description': 'Entendemos por qué tus visitantes no compran, con datos.',
    'relatedServices.services.conversionAudit.title': 'Auditoría de conversión',
    'relatedServices.services.conversionAudit.description': 'Un plan de acción priorizado por impacto para vender más.',
    'relatedServices.services.landingPages.title': 'Optimización de landing pages',
    'relatedServices.services.landingPages.description': 'Páginas clave rediseñadas con un único objetivo: convertir.',
    'relatedServices.services.emailAutomation.title': 'Email marketing automation',
    'relatedServices.services.emailAutomation.description': 'Flujos automáticos que venden mientras duermes.',
    'relatedServices.services.emailCampaigns.title': 'Campañas de email',
    'relatedServices.services.emailCampaigns.description': '8 emails al mes que mantienen tu marca presente.',
    'relatedServices.services.maintenance.title': 'Mantenimiento',
    'relatedServices.services.maintenance.description': 'Tu tienda siempre al día, sin contratar a nadie.',

    // Blog
    'blog.title': 'SellifyWorks Blog',
    'blog.subtitle': 'Artículos y consejos sobre Shopify, ecommerce y crecimiento online',
    'blog.heroPost': 'Artículo Destacado',
    'blog.moreStories': 'Más Artículos',
    'blog.readMore': 'Leer más',
    'blog.publishedOn': 'Publicado el',
    'blog.by': 'por',
    'blog.backToBlog': '← Volver al Blog',
    'blog.relatedPosts': 'Artículos Relacionados',
    'blog.shareArticle': 'Compartir artículo',
    'blog.tags': 'Etiquetas',
    'blog.categories': 'Categorías',
  },
  en: {
    // Navbar
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',

    // Hero
    'hero.eyebrow': 'Shopify agency · Spain',
    'hero.title.line1': 'Enterprise-grade Shopify.',
    'hero.title.line2': 'Finally accessible.',
    'hero.sub': 'You\'ve got traffic, but it doesn\'t convert. We help you fix it with the same processes the big brands use — at the price of your stage.',
    'hero.cta1': 'Talk to an expert',
    'hero.cta2': 'See services & pricing',
    'hero.stat1.label': 'conversions/month — our sweet spot',
    'hero.stat2.label': 'full Shopify migration, turnkey',
    'hero.stat3.num': 'AI',
    'hero.stat3.label': 'enterprise process, small-brand cost',

    // Problem + For whom (merged section: short statement + checklist)
    'problem.eyebrow': 'The problem',
    'problem.title': 'Agencies chase the big players.',
    'problem.lede': 'Your store doesn\'t have a product problem. It has a conversion problem — and you\'ll know if this sounds like you:',
    'whom.item1': 'You sell on Shopify — or you want to migrate to it.',
    'whom.item2': 'Traffic comes in, but conversions don\'t follow.',
    'whom.item3': 'You want to grow and don\'t know where to start.',
    'whom.item4': 'You don\'t have an enterprise budget — and you shouldn\'t need one.',
    'whom.item5': 'Your agency, if you have one, isn\'t looking out for you.',
    'whom.foot': 'Exactly who we\'re here for.',

    // Close / CTA
    'close.eyebrow': 'Let\'s start',
    'close.title': 'Your store deserves better.',
    'close.cta': 'Start with an audit',

    // Contact Section
    'contact.title': 'Let\'s talk.',
    'contact.description': 'Tell us what\'s going on with your store. We\'ll reply to set up a call, no strings attached.',
    'contact.form.title': 'TELL US ABOUT YOUR PROJECT',
    'contact.form.name': 'Your name',
    'contact.form.name.label': 'Name *',
    'contact.form.email': 'your@email.com',
    'contact.form.email.label': 'Email *',
    'contact.form.phone': 'Phone',
    'contact.form.company': 'Your store / brand',
    'contact.form.company.label': 'Company',
    'contact.form.message': 'Tell us about your project...',
    'contact.form.message.label': 'Message *',
    'contact.form.submit': 'Send message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message sent successfully! We will contact you soon.',
    'contact.form.name.req': 'Tell us your name',
    'contact.form.name.ok': 'Great',
    'contact.form.email.req': 'We need your email',
    'contact.form.email.bad': 'That email doesn\'t look valid',
    'contact.form.email.ok': 'Valid email',
    'contact.form.company.ok': 'Got it',
    'contact.form.message.req': 'Tell us a bit about your store',
    'contact.form.message.short': 'A little more context, please',
    'contact.form.message.ok': 'Done',
    'contact.form.err': 'Check the highlighted fields.',
    'contact.info.phone': 'Phone',
    'contact.info.email': 'Email',
    'contact.info.location': 'Location',

    // Footer
    'footer.newsletter.title': 'STAY UP TO DATE',
    'footer.newsletter.description': 'Get the latest e-commerce trends, Shopify tips and news from our agency directly in your inbox.',
    'footer.newsletter.placeholder': 'your@email.com',
    'footer.newsletter.button': 'Subscribe',
    'footer.newsletter.sending': 'Sending...',
    'footer.newsletter.success': 'Check your email to confirm!',
    'footer.newsletter.already': 'Already subscribed!',
    'footer.newsletter.subscribed': 'Subscribed!',
    'footer.newsletter.error': 'Subscription error',
    'footer.newsletter.connection_error': 'Connection error. Please try again.',
    'footer.company': 'SELLIFYWORKS',
    'footer.description': 'E-commerce agency specialized in Shopify. We create, optimize and grow online stores that convert.',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.cookies': 'Cookie Policy',
    
    // Footer Services
    'footer.services.title': 'SERVICES',
    'footer.services.migration': 'Shopify migration',
    'footer.services.migrationPlus': 'Migration Plus',
    'footer.services.customDev': 'Custom development',
    'footer.services.conversionResearch': 'Conversion research',
    'footer.services.conversionAudit': 'Conversion audit',
    'footer.services.landingPages': 'Landing page optimization',
    'footer.services.emailAutomation': 'Email marketing automation',
    'footer.services.emailCampaigns': 'Email campaigns',
    'footer.services.maintenance': 'Maintenance',

    // Services Section (pricing)
    'services.eyebrow': 'Services & pricing',
    'services.title': 'Clear pricing.',
    'services.sub': 'No inflated bundles, no fine print. Pick what your store needs now and scale when it makes sense.',
    'services.group.foundation.name': 'Foundation',
    'services.group.foundation.desc': 'A store built to sell, not just to exist.',
    'services.group.conversion.name': 'Conversion',
    'services.group.conversion.desc': 'You don\'t need more visits, you need to sell more to the ones you already have.',
    'services.group.recurring.name': 'Recurring revenue',
    'services.group.recurring.desc': 'Turn one purchase into a customer who comes back.',
    'services.migration.name': 'Shopify migration',
    'services.migration.tagline': 'For migrating without losing sales',
    'services.migration.bullet1': 'Full audit before moving anything',
    'services.migration.bullet2': 'Upload and copy for your whole catalog',
    'services.migration.bullet3': 'Zero downtime',
    'services.migrationPlus.name': 'Migration Plus',
    'services.migrationPlus.tag': 'Recommended',
    'services.migrationPlus.tagline': 'For stores already past €4,000/month',
    'services.migrationPlus.bullet1': 'Everything in Migration',
    'services.migrationPlus.bullet2': 'Conversion research included',
    'services.migrationPlus.bullet3': 'Launch optimized from day one',
    'services.customDev.name': 'Custom development',
    'services.customDev.tagline': 'For what doesn\'t fit any plan',
    'services.customDev.bullet1': 'Integrations with your tools',
    'services.customDev.bullet2': 'Custom automations',
    'services.customDev.bullet3': 'Fixed quote before we start',
    'services.customDev.price': 'Custom',
    'services.conversionResearch.name': 'Conversion research',
    'services.conversionResearch.tagline': 'For understanding why they don\'t buy',
    'services.conversionResearch.bullet1': 'Google Analytics analysis',
    'services.conversionResearch.bullet2': 'Real qualitative research',
    'services.conversionResearch.bullet3': 'Actionable report, no jargon',
    'services.conversionAudit.name': 'Conversion audit',
    'services.conversionAudit.tagline': 'For knowing what to fix first',
    'services.conversionAudit.bullet1': 'Full funnel review',
    'services.conversionAudit.bullet2': 'Prioritized by sales impact',
    'services.conversionAudit.bullet3': 'Concrete next steps',
    'services.landingPages.name': 'Landing page optimization',
    'services.landingPages.tagline': 'For your highest-traffic page',
    'services.landingPages.bullet1': 'Proven CRO heuristics',
    'services.landingPages.bullet2': 'Optimized CTAs and trust signals',
    'services.landingPages.bullet3': 'Priced per page, no bundles',
    'services.emailAutomation.name': 'Email marketing automation',
    'services.emailAutomation.tagline': 'For selling while you sleep',
    'services.emailAutomation.bullet1': 'Welcome flow and abandoned cart',
    'services.emailAutomation.bullet2': 'Post-purchase and review request',
    'services.emailAutomation.bullet3': 'Set up, tested, ready to go',
    'services.emailCampaigns.name': 'Monthly email campaigns',
    'services.emailCampaigns.tagline': 'For keeping your list warm',
    'services.emailCampaigns.bullet1': 'Monthly content strategy',
    'services.emailCampaigns.bullet2': 'Design and implementation included',
    'services.emailCampaigns.bullet3': '8 sends a month',
    'services.maintenance.name': 'Maintenance',
    'services.maintenance.tagline': 'So your store isn\'t abandoned between projects',
    'services.maintenance.bullet1': '10 small tasks a month',
    'services.maintenance.bullet2': 'No hiring needed',
    'services.maintenance.bullet3': 'Bigger tasks, quoted separately',
    'services.unit.iva': '+ VAT',
    'services.cta': 'Let\'s talk about your store',
    'services.viewDetail': 'View details',
    'services.note': 'Maintenance task examples are indicative. SellifyWorks decides, based on the time and complexity of each task, whether it\'s part of maintenance or requires separate development. Prices exclude VAT.',

    // Case Study Section
    'casestudy.badge': 'Real case',
    'casestudy.title': 'Can Ramos: from stuck on Wix to a Shopify store that sells itself',
    'casestudy.subtitle': 'They had traffic. The platform wouldn\'t let them convert it.',
    'casestudy.challenge.title': 'The problem',
    'casestudy.challenge.description': 'Slow loading, confusing checkout, zero email marketing. Can Ramos already had customers — every visit that didn\'t convert was money left on the table.',
    'casestudy.solution.title': 'What we did',
    'casestudy.solution.description': 'Migrated to Shopify without losing a single sale or data point. A store with their real identity, checkout upsells, and a welcome flow that sells on its own.',
    'casestudy.results.title': 'The result',
    'casestudy.result1': 'Design with real identity: more trust, more conversions',
    'casestudy.result2': 'Welcome flow selling on autopilot, 24/7',
    'casestudy.result3': 'Higher average ticket with checkout upsells',
    'casestudy.result4': 'Faster loading, fewer checkout drop-offs',
    'casestudy.result5': 'Zero losses: products, customers and SEO intact',
    'casestudy.expertise.title': 'Why it worked',
    'casestudy.expertise.description': 'We audited what was slowing sales down, redesigned with conversion in mind, and automated what used to be manual.',
    'casestudy.expertise.tag1': 'Design with identity',
    'casestudy.expertise.tag2': 'Automated email',
    'casestudy.expertise.tag3': 'Higher average ticket',
    'casestudy.cta.title': 'Is your store limiting you?',
    'casestudy.cta.description': 'If you have traffic but feel you should be selling more, let\'s talk. We\'ll show you what\'s holding back your conversions.',
    'casestudy.cta.button': 'Get a free call',
    'casestudy.cta.viewcase': 'See the real store',
    
    // About Page
    'about.hero.title': 'ABOUT US',
    'about.hero.subtitle': 'We create exceptional e-commerce experiences on Shopify.',
    'about.history.title': 'OUR STORY',
    'about.history.content': 'This project started with a clear vision: to improve the shopping experience in e-commerce through high-quality technical solutions focused on Shopify. From that idea, SellifyWorks grew as a results-oriented technical consultancy, with an agile, scalable and customer-centered work model.',
    'about.mission.title': 'OUR MISSION',
    'about.mission.content': 'We drive e-commerce businesses through personalized technical solutions on Shopify. We focus on automating processes, optimizing store performance and applying agile methodologies that ensure fast and high-quality deliveries.\n\nOur goal is for each client to be able to scale without worrying about technical complexity, trusting a consultancy that puts user experience and operational efficiency at the center of every decision.',
    'about.values.title': 'OUR VALUES',
    'about.values.subtitle': 'The principles that guide our work and define who we are.',
    'about.values.quality.title': 'QUALITY',
    'about.values.quality.content': 'We apply development practices like Extreme Programming because we believe that a good solution should not only work, but work well, fast and sustainably.',
    'about.values.validation.title': 'VALIDATION',
    'about.values.validation.content': 'We believe in the importance of validating ideas and solutions through constant testing and real feedback. This allows us to adjust and improve our approaches, ensuring we are always on the right track.',
    'about.values.transparency.title': 'TRANSPARENCY',
    'about.values.transparency.content': 'We believe in honest relationships, in iterative processes that allow constant evolution, and in the non-negotiable commitment to deliver value in every delivery.',
    'about.team.title': 'OUR TEAM',
    'about.team.subtitle': 'Meet the people who make your project\'s success possible.',
    'about.team.mathias.role': 'FOUNDER',
    'about.team.mathias.description': 'Computer engineer with over 10 years of experience in software development.',
    'about.cta.title': 'READY TO WORK TOGETHER?',
    'about.cta.subtitle': 'Discover how we can help you take your business to the next level.',
    'about.cta.button': 'Contact us',
    
    // Newsletter Confirmed Page
    'newsletter.confirmed.success.title': 'Subscription Confirmed!',
    'newsletter.confirmed.success.message': 'Thank you for confirming your subscription to our newsletter. You will now receive our exclusive tips on Shopify and e-commerce.',
    'newsletter.confirmed.already.title': 'Already subscribed!',
    'newsletter.confirmed.already.message': 'Your email is already subscribed to our newsletter. No need to confirm again.',
    'newsletter.confirmed.error.title': 'Confirmation Error',
    'newsletter.confirmed.error.message': 'There was a problem confirming your subscription. The link may have expired or be invalid.',
    'newsletter.confirmed.back': 'Back to Home',
    'newsletter.confirmed.loading': 'Loading...',
    
    // 404 Page
    '404.title': 'PAGE NOT FOUND',
    '404.description': 'It looks like the page you\'re looking for went on vacation to a remote beach. In the meantime, how about we explore together what we do have?',
    '404.suggestion': 'Or maybe our developer had too many coffees and moved something by mistake... 🤔',
    '404.buttons.home': 'Back to Home',
    '404.buttons.back': 'Previous Page',
    '404.buttons.contact': 'Contact Us',
    
    // Privacy Policy Page
    'privacy.title': 'PRIVACY POLICY',
    'privacy.subtitle': 'Last updated: August 2024',
    'privacy.section1.title': 'Information We Collect',
    'privacy.section1.content': 'At SellifyWorks, we collect personal information that you voluntarily provide to us when you contact us, subscribe to our newsletter, or use our services.',
    'privacy.section2.title': 'Types of Data',
    'privacy.section2.content': 'The types of personal information we may collect include:',
    'privacy.section2.item1': 'First and last name',
    'privacy.section2.item2': 'Email address',
    'privacy.section2.item3': 'Phone number',
    'privacy.section2.item4': 'Information about your company or project',
    'privacy.section3.title': 'How We Use Your Information',
    'privacy.section3.content': 'We use the personal information we collect to provide our services, respond to your inquiries, send you our newsletter (if you have subscribed), and improve our services.',
    'privacy.section4.title': 'Data Protection',
    'privacy.section4.content': 'We implement appropriate technical and organizational security measures to protect your personal information against unauthorized access, alteration, disclosure or destruction.',
    'privacy.section5.title': 'Your Rights',
    'privacy.section5.content': 'You have the right to access, rectify, delete and port your personal data. You can also object to processing and request limitation of the same.',
    'privacy.contact.title': 'Contact',
    'privacy.contact.content': 'If you have questions about this privacy policy, you can contact us at:',
    'privacy.back': 'Back to Home',
    
    // Cookie Policy Page
    'cookies.title': 'COOKIE POLICY',
    'cookies.subtitle': 'Last updated: August 2024',
    'cookies.section1.title': 'What are Cookies?',
    'cookies.section1.content': 'Cookies are small text files that are stored on your device when you visit our website. They help us improve your browsing experience and understand how you use our site.',
    'cookies.section2.title': 'Types of Cookies We Use',
    'cookies.section2.essential.title': 'Essential Cookies',
    'cookies.section2.essential.content': 'These cookies are necessary for the basic functioning of the website and cannot be disabled.',
    'cookies.section2.analytics.title': 'Analytics Cookies',
    'cookies.section2.analytics.content': 'They help us understand how visitors interact with our website by collecting information anonymously.',
    'cookies.section2.preferences.title': 'Preference Cookies',
    'cookies.section2.preferences.content': 'We remember your preferences, such as selected language, to improve your experience.',
    'cookies.section3.title': 'Cookie Control',
    'cookies.section3.content': 'You can control and/or delete cookies as you wish. You can delete all cookies that are already on your device and set most browsers to prevent them from being installed.',
    'cookies.section4.title': 'More Information',
    'cookies.section4.content': 'If you disable cookies, some website features may not work properly.',
    'cookies.contact.title': 'Contact',
    'cookies.contact.content': 'If you have questions about our cookie policy, you can contact us at:',
    'cookies.back': 'Back to Home',
    
    // Related Services
    'relatedServices.title': 'RELATED SERVICES',
    'relatedServices.subtitle': 'Discover other services that can boost your Shopify store',
    'relatedServices.learnMore': 'Learn more',
    'relatedServices.services.migration.title': 'Shopify migration',
    'relatedServices.services.migration.description': 'Migrate your store to Shopify without losing data or interrupting sales.',
    'relatedServices.services.migrationPlus.title': 'Migration Plus',
    'relatedServices.services.migrationPlus.description': 'Migration + conversion research to launch optimized from day one.',
    'relatedServices.services.customDev.title': 'Custom development',
    'relatedServices.services.customDev.description': 'Custom functionality, integrations and automations.',
    'relatedServices.services.conversionResearch.title': 'Conversion research',
    'relatedServices.services.conversionResearch.description': 'We learn why your visitors don\'t buy, with real data.',
    'relatedServices.services.conversionAudit.title': 'Conversion audit',
    'relatedServices.services.conversionAudit.description': 'An action plan prioritized by impact to sell more.',
    'relatedServices.services.landingPages.title': 'Landing page optimization',
    'relatedServices.services.landingPages.description': 'Key pages redesigned with one goal: converting.',
    'relatedServices.services.emailAutomation.title': 'Email marketing automation',
    'relatedServices.services.emailAutomation.description': 'Automated flows that sell while you sleep.',
    'relatedServices.services.emailCampaigns.title': 'Email campaigns',
    'relatedServices.services.emailCampaigns.description': '8 emails a month that keep your brand top of mind.',
    'relatedServices.services.maintenance.title': 'Maintenance',
    'relatedServices.services.maintenance.description': 'Your store always up to date, no hire needed.',

    // Blog
    'blog.title': 'SellifyWorks Blog',
    'blog.subtitle': 'Articles and tips about Shopify, ecommerce and online growth',
    'blog.heroPost': 'Featured Article',
    'blog.moreStories': 'More Stories',
    'blog.readMore': 'Read more',
    'blog.publishedOn': 'Published on',
    'blog.by': 'by',
    'blog.backToBlog': '← Back to Blog',
    'blog.relatedPosts': 'Related Posts',
    'blog.shareArticle': 'Share article',
    'blog.tags': 'Tags',
    'blog.categories': 'Categories',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const pathname = usePathname()
  // Se deriva del pathname ya en el primer render (incluido SSR) para evitar
  // que /en parpadee en español hasta que el useEffect corrija el estado.
  const [language, setLanguage] = useState<Language>(() => (pathname.startsWith('/en') ? 'en' : 'es'))

  // Mantener sincronizado si el pathname cambia tras la navegación inicial
  useEffect(() => {
    setLanguage(pathname.startsWith('/en') ? 'en' : 'es')
  }, [pathname])

  // Guardar idioma en localStorage cuando cambie
  useEffect(() => {
    localStorage.setItem('language', language)
  }, [language])

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['es']] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
